# Generated by Django 5.2.6 on 2025-09-19 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Secretaria')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
        ),
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Divisão')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Divisão',
                'verbose_name_plural': 'Divisões',
            },
        ),
        migrations.CreateModel(
            name='CartaDeServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=255, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('prazo_maximo_dias', models.PositiveIntegerField(help_text='Prazo máximo em dias corridos para a conclusão do serviço.')),
                ('divisao_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.divisao', verbose_name='Divisão Responsável')),
            ],
            options={
                'verbose_name': 'Serviço da Carta',
                'verbose_name_plural': 'Carta de Serviços',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número do Protocolo')),
                ('solicitante', models.CharField(max_length=255, verbose_name='Solicitante')),
                ('data_protocolo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Protocolo')),
                ('data_prazo', models.DateField(verbose_name='Prazo Final')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em Análise'), ('PENDENTE', 'Pendente de Informação'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20, verbose_name='Status')),
                ('detalhes_solicitacao', models.TextField(verbose_name='Detalhes da Solicitação')),
                ('responsavel_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável Atual')),
                ('servico_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cartadeservicos', verbose_name='Serviço Solicitado')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secretaria', verbose_name='Secretaria'),
        ),
    ]
