# Generated by Django 5.2.6 on 2025-09-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolucaoDeOperacaoDoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_passos', models.TextField(help_text='Descreva o passo a passo interno para executar o serviço.')),
                ('sistemas_utilizados', models.CharField(blank=True, max_length=255)),
                ('carta_de_servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cartadeservicos')),
            ],
        ),
    ]
