# Generated by Django 5.2.6 on 2025-11-07 14:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Entidade')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.AddField(
            model_name='cartadeservicos',
            name='forma_solicitacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema de Origem'),
        ),
        migrations.AddField(
            model_name='cartadeservicos',
            name='orgao_responsavel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Órgão (ex: Procon)'),
        ),
        migrations.AddField(
            model_name='cartadeservicos',
            name='tipo_servico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo (Serviço ou Informação)'),
        ),
        migrations.AddField(
            model_name='cartadeservicos',
            name='tipo_sistema',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo do Sistema (Próprio, Terceirizado)'),
        ),
        migrations.AddField(
            model_name='cartadeservicos',
            name='tipos_atendimento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipos de Atendimento'),
        ),
        migrations.AddField(
            model_name='cartadeservicos',
            name='url_solicitacao',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link para Solicitação'),
        ),
        migrations.AddField(
            model_name='processo',
            name='localizacao',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localização Geográfica'),
        ),
        migrations.AlterField(
            model_name='cartadeservicos',
            name='prazo_maximo_dias',
            field=models.PositiveIntegerField(default=30, help_text='Prazo máximo em dias corridos.'),
        ),
        migrations.AddField(
            model_name='cartadeservicos',
            name='entidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.entidade', verbose_name='Entidade'),
        ),
    ]
