# Generated by Django 5.2.6 on 2025-11-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entidade_cartadeservicos_forma_solicitacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeamentoServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_origem', models.CharField(choices=[('COLAB', 'Colab'), ('1DOC', '1Doc'), ('APROVA_DIGITAL', 'Aprova Digital'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Sistema de Origem')),
                ('categoria_externa', models.CharField(max_length=255, verbose_name='Categoria no Sistema de Origem')),
                ('servico_gea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cartadeservicos', verbose_name='Serviço Correspondente no GEA')),
            ],
            options={
                'verbose_name': 'Mapeamento de Serviço Externo',
                'verbose_name_plural': 'Mapeamentos de Serviços',
                'unique_together': {('sistema_origem', 'categoria_externa')},
            },
        ),
    ]
