# Generated by Django 5.2.6 on 2025-11-17 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='data_protocolo',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Protocolo'),
        ),
    ]
