# Generated by Django 5.2.6 on 2025-11-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_processo_data_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='sistema_origem',
            field=models.CharField(choices=[('COLAB', 'Colab'), ('1DOC', '1Doc'), ('APROVA_DIGITAL', 'Aprova Digital'), ('OUTRO', 'Outro')], default='OUTRO', max_length=50, verbose_name='Sistema de Origem (Histórico)'),
        ),
    ]
